---
title: "Assignment 1"
author: "Andresa Andrade"
date: "October 4, 2015"
output: pdf_document
---


<div id="toc">
<ul><li>


# <a href="#toc_1">Abstract</a>

In recent years understand what are the factors that lead a buy to finalize a conversion has become one of the most important problems of online marketing business. The purpose of this project is to understand any possible pattern in the customer behavior of an online shop and try to predict the types of coupons that the customers would want to use/buy. 

Along the way we shall show the structure of categorization and how the machine learning algorithm would work for this particular case. We also will present the conditions assumed in order to have the model working properly. And the facts ignored but also important to a througoly analysis. 

We will also show the evaluation methods between the different methodologies here presented.

<ul> <li>
# <a href="#toc_1">Introduction</a>
In this paper and the follow documents presented along the way of this project, we will attempt to demonstrate if the online browsing history is correlated to final purchase. 

For that we will be using four data files to learn from the data. The first file is composed with the list of 22.874 customers and some personal information that will be described in the dataset section. The second file to be used is a file that contains information related to users buying voucher. And the third file to be used contain the data related to users browsing in the site. The last file to be used is the coupon detail information that contains all the data specifically about the coupon.

<ul><li>

# <a href="#Background</a>


<ul><li>
# <a href="#toc_1">Related Literature</a>

Because this dataset was adquired from Kaggle website, it's assumed that there are several other solutions that could be used to compare the results. Nevertheless this problem is not unusual within the statistic environment. Since the beggining of the days

<ul> <li>
</div>